# Generated by Django 3.2.6 on 2021-11-11 20:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='long_descriptions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
