# Generated by Django 3.2.6 on 2021-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_long_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='long_descriptions',
            field=models.TextField(null=True),
        ),
    ]
